### ISSUE TITLE
[Feature request] Upgrade to http 1.0.0

### ISSUE THREAD

**Issue by delfme** [fluttercandies/http_client_helper#10]
### Platforms

iOS

### Description

Hello,
Could you please upgrade the package to v 1.0.0 ?

### Why

flutter http 0.13.0 has several issues on iOS, mostly http connection performance has been improved a lot since then.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/http_client_helper/issues/8

**Comment by delfme** [comment]
Thx! Didnt notice it was answered elsewhere.
