### ISSUE TITLE
Bad Certificate

### ISSUE THREAD

**Issue by SatExo** [fluttercandies/http_client_helper#3]
Hi,
Thanks for making this excellent library.  It helps me (a noob) a lot.  I was wondering if you could help me on how to set the https request to accept any self signed certificate;  I tried setting client.badCertificateCallback = (X509Certificate cert, String host, int port)=> true; in my code but that doesn't seem to work.
If you have any idea your expert knowledge would be appreciated
Thanks
Michaël

**Comment by zmtzawqlp** [comment]
you can do as following code:  
``` dart   
    HttpClient http = HttpClient();
    http.badCertificateCallback =
        (X509Certificate cert, String host, int port) {
      return true;
    };
    HttpClientHelper.set(http);
  ```
