### ISSUE TITLE
Why is the set method not static?

### ISSUE THREAD

**Issue by fmestrone** [fluttercandies/http_client_helper#4]
I switched to this HTTP client instead of the core one because I wanted to be able to write tests for my backend services and this allows me to set the HTTP client so that I can inject a mock.
One question though: why isn't the set method static? You are forcing me to create an instance that has no use and I don't need, or maybe I'm missing something? Thanks

```
    test('HTTP error on GET /endpoint', () async {
      var httpMockClient = MockClient((request) async {
        return Response('Server Error', 500);
      });
      //** Why this:
      HttpClientHelper().set(httpMockClient);
      //** Instead of simply this:
      HttpClientHelper.set(httpMockClient);
      //** or better still:
      HttpClientHelper.setClient(httpMockClient);
      expect(() async => model.getUserLocations(), throwsA(allOf(
        isA<UserLocationsException>()
            .having((e) => e.message, 'message', 'HTTP Error 500'),
      )));
    });
```

**Comment by zmtzawqlp** [comment]
yes, you are right，I'm sorry for that, i will update this in issue.
``` dart
 HttpClientHelper.set(httpMockClient);
```

**Comment by fmestrone** [comment]
If I may suggest, I think setClient would be a clearer name for this method ;)
Any ETA for this? it should be a pretty straightforward change, happy to submit a PR if that helps

**Comment by zmtzawqlp** [comment]
Thanks, but this package is stable, i don't want to make any breaking change for now. i will update it when something must be a breaking change together.

**Comment by ming-chu** [comment]
https://github.com/fluttercandies/http_client_helper/pull/7

I added a static setter `setClient` which will not leading any breaking changes.
Feel free to ignore if it doesn't help.
