### ISSUE TITLE
Cancel Token not working

### ISSUE THREAD

**Issue by LtotheWT** [fluttercandies/http_client_helper#6]
![Screenshot 2022-06-07 at 12 05 19 PM](https://user-images.githubusercontent.com/13746657/172293809-87f8dbee-4e8b-4ac7-a9da-d7b2cd599920.png)

start request
cancel request
end request 200

the request still running even i had triggered the .cancel

**Comment by JayronKhong** [comment]
i have same issue, is this package still working?

**Comment by zmtzawqlp** [comment]
there is no real cancel, it's competed with cancel exception. you should catch it

**Comment by JayronKhong** [comment]
I did tested the example that you provide on the package, also not working.

**Comment by zmtzawqlp** [comment]
please upgrade to 2.0.3, reopen issue if there is any other issue
