### ISSUE TITLE
Upgrade dependency to http 1.0.0 [Feature request] 

### ISSUE THREAD

**Issue by stingrayx** [fluttercandies/http_client_helper#8]
### Platforms

dart

### Description

It would be great if the plugin dependency to http could be upgrade to align with latest version 1.0.0

Many plugins start to require http 1.0.0, which makes it hard to upgrade in case extended_image 8.0.1 is also used, because of it's dependency chain

**Comment by zmtzawqlp** [comment]
http require dart 3.0.0 and extended_image not require. you can  use dependency_overrides to override http at your side

**Comment by pattern-realms** [comment]
hello... Thank you for this helpful library! The issue occurs in the package extended_image depends on extended_image_library which depends on http_client_helper which depends on http 0.13.0 which conflicts with other packages that have adopted http 1.0.0.  I think in this case a consumer of extended_image then needs to to upgrade the entire stack which is arduous.  It would be helpful to have a version that adopts the http 1.0.0; it is likely simply a yaml change.

I am not aware of a way to override a dependency in an incoming package, especially when it is imported from three levels down... perhaps there are yaml tricks that would do this.  Thank you again for your contributions.

edit: clarity

**Comment by zmtzawqlp** [comment]
you can add as following in your main project:

``` yaml
dependency_overrides:
    http: 1.0.0
```

**Comment by pattern-realms** [comment]
Adding the dependency_overrides fixed the issue. Enjoy.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/http_client_helper/commit/5c71e745d964bb82c63e407e01805c295d7d192b  done
